-- Insert categories
INSERT INTO Categories (CategoryName, Description)
VALUES
('Electronics', 'Electronics category'),
('Fashion', 'Fashion category'),
('Home and Kitchen', 'Home and kitchen category');

-- Insert products
INSERT INTO Products (ProductName, Description, BasePrice, Quantity, CategoryID)
VALUES
('Samsung TV', 'Samsung 4K TV', 999.99, 10, 1),
('Apple Watch', 'Apple Watch Series 7', 399.99, 20, 2),
('Nike Shoes', 'Nike Running Shoes', 79.99, 50, 2),
('Kitchen Appliance', 'Kitchen Appliance Set', 199.99, 30, 3),
('Laptop', 'Dell Laptop', 999.99, 15, 1);

-- Insert product categories
INSERT INTO ProductCategories (ProductID, CategoryID)
VALUES
(1, 1),
(2, 2),
(3, 2),
(4, 3),
(5, 1);

-- Insert customers
INSERT INTO Customers (FirstName, LastName, Email, PasswordHash, Address, City, State, Country, PostalCode)
VALUES
('John', 'Doe', 'john.doe@example.com', 'password123', '123 Main St', 'New York', 'NY', 'USA', '10001'),
('Jane', 'Doe', 'jane.doe@example.com', 'password123', '456 Elm St', 'Los Angeles', 'CA', 'USA', '90001'),
('Bob', 'Smith', 'bob.smith@example.com', 'password123', '789 Oak St', 'Chicago', 'IL', 'USA', '60601'),
('Alice', 'Johnson', 'alice.johnson@example.com', 'password123', '321 Pine St', 'Houston', 'TX', 'USA', '77001'),
('Mike', 'Williams', 'mike.williams@example.com', 'password123', '901 Maple St', 'Phoenix', 'AZ', 'USA', '85001');

-- Insert orders
INSERT INTO Orders (CustomerID, OrderDate, TotalAmount)
VALUES
(1, '2022-01-01', 999.99),
(1, '2022-01-15', 399.99),
(2, '2022-02-01', 79.99),
(3, '2022-03-01', 199.99),
(4, '2022-04-01', 999.99),
(5, '2022-05-01', 399.99),
(1, '2022-06-01', 999.99),
(2, '2022-07-01', 79.99),
(3, '2022-08-01', 199.99),
(4, '2022-09-01', 999.99),
(5, '2022-10-01', 399.99);

-- Insert order items
INSERT INTO Order_Items (OrderID, ProductID, Quantity, PriceAtOrder)
VALUES
(1, 1, 1, 999.99),
(2, 2, 1, 399.99),
(3, 3, 2, 79.99),
(4, 4, 1, 199.99),
(5, 5, 1, 999.99),
(6, 1, 1, 999.99),
(7, 2, 1, 399.99),
(8, 3, 2, 79.99),
(9, 4, 1, 199.99),
(10, 5, 1, 999.99),
(11, 1, 1, 999.99),
(12, 2, 1, 399.99),
(13, 3, 2, 79.99),
(14, 4, 1, 199.99),
(15, 5, 1, 999.99);

-- Insert shipments
INSERT INTO Shipments (OrderID, TrackingNumber, ShipmentDate, ShippingMethod)
VALUES
(1, '123456789', '2022-01-02', 'UPS'),
(2, '987654321', '2022-01-16', 'FedEx'),
(3, '111111111', '2022-02-02', 'USPS'),
(4, '222222222', '2022-03-02', 'UPS'),
(5, '333333333', '2022-04-02', 'FedEx'),
(6, '444444444', '2022-06-02', 'USPS'),
(7, '555555555', '2022-07-02', 'UPS'),
(8, '666666666', '2022-08-02', 'FedEx'),
(9, '777777777', '2022-09-02', 'USPS'),
(10, '888888888', '2022-10-02', 'UPS');






-- Retrieve the top 5 customers who have made the most orders
SELECT TOP 5 o.CustomerID, COUNT(o.OrderID) AS TotalOrders
FROM Orders o
INNER JOIN Customers c ON o.CustomerID = c.CustomerID
GROUP BY o.CustomerID
ORDER BY TotalOrders DESC;

-- Display the total revenue generated by each product category
SELECT c.CategoryName, SUM(oi.PriceAtOrder * oi.Quantity) AS TotalRevenue
FROM Products p
INNER JOIN ProductCategories pc ON p.ProductID = pc.ProductID
INNER JOIN Categories c ON pc.CategoryID = c.CategoryID
INNER JOIN Order_Items oi ON p.ProductID = oi.ProductID
GROUP BY c.CategoryName;

-- Find the number of orders placed in the last month, broken down by day
SELECT DATEPART(day, o.OrderDate) AS Day, COUNT(o.OrderID) AS TotalOrders
FROM Orders o
WHERE o.OrderDate >= DATEADD(month, -1, GETDATE())
GROUP BY DATEPART(day, o.OrderDate)
ORDER BY Day;

-- Calculate the average order value for each customer
SELECT c.CustomerID, AVG(o.TotalAmount) AS AverageOrderValue
FROM Orders o
INNER JOIN Customers c ON o.CustomerID = c.CustomerID
GROUP BY c.CustomerID;
